spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_management_system
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
